version: "3.7"

services: 
  mongodb:
    image: mongo:4.2.0-bionic
  
  app:
    build:
      context: .
    command:  /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "8080:8080"
    volumes: 
      - type: bind
        source: .
        target: /home/vscode/dev
